import express from 'express';
import request from 'supertest';
import { afterAll, beforeAll, describe, expect, it, vi } from 'vitest';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const authRoutes = require('../src/auth/authRoutes');
const exampleRuleRoutes = require('../src/example-rule-check/exampleRuleRoutes');
const repo = require('../src/example-rule-check/exampleRuleRepository');
const service = require('../src/example-rule-check/exampleRuleService');
const { createTestDatabaseHarness } = require('../src/database');

const app = express(); app.use(express.json()); app.use('/api/auth', authRoutes); app.use('/api/example-rule-check', exampleRuleRoutes);
let harness; let student; let supervisor; let originalDir;
const valid = { name:'数据支撑检查', intent:'检查结论是否有数据支撑', status:'enabled', definition:{title:'数据支撑检查',check_description:'检查关键结论',criteria:['关键结论应有对应数据'],exception_notes:[],suggestion_template:'补充数据'} };
async function login(username){const r=await request(app).post('/api/auth/login').send({username,password:'ArcDemo123!'}).expect(200);return r.headers['set-cookie'].find(x=>x.startsWith('arc_session='));}
describe('example rule check HTTP bridge',()=>{beforeAll(async()=>{originalDir=process.env.EXAMPLE_RULE_REPORTS_DIR;process.env.EXAMPLE_RULE_REPORTS_DIR=`${process.cwd()}/.arc-test-example-rule-${Date.now()}`;harness=createTestDatabaseHarness({label:'example-rule-check',seedDefault:true});await harness.setup();student=await login('student01');supervisor=await login('supervisor01');});afterAll(async()=>{if(originalDir===undefined)delete process.env.EXAMPLE_RULE_REPORTS_DIR;else process.env.EXAMPLE_RULE_REPORTS_DIR=originalDir;await harness.cleanup();});
it('rejects anonymous access and cross-user reads/deletes',async()=>{await request(app).get('/api/example-rule-check/rules').expect(401);const created=(await request(app).post('/api/example-rule-check/rules').set('Cookie',student).send(valid).expect(201)).body;await request(app).get(`/api/example-rule-check/rules/${created.id}`).set('Cookie',supervisor).expect(404);await request(app).delete(`/api/example-rule-check/rules/${created.id}`).set('Cookie',supervisor).expect(404);await request(app).get(`/api/example-rule-check/rules/${created.id}`).set('Cookie',student).expect(200);});
it('validates input and requires external-processing consent before generation',async()=>{await request(app).post('/api/example-rule-check/rules').set('Cookie',student).send({...valid,name:''}).expect(400);await request(app).post('/api/example-rule-check/generate').set('Cookie',student).send({intent:'检查',document_ids:[]}).expect(400).expect(r=>expect(r.body.message).toContain('确认'));});
it('increments rule versions and preserves report rule snapshots',async()=>{const created=(await request(app).post('/api/example-rule-check/rules').set('Cookie',student).send({...valid,name:'快照规则'}).expect(201)).body;const pdf=Buffer.from('%PDF-1.4\nexample');const report=await repo.createReport('student01','论文.pdf',pdf,[{rule_id:created.id,name:created.name,version:created.version,definition:created.definition}],{summary:{rule_count:1,issue_count:0},rule_results:[]});const changed=(await request(app).put(`/api/example-rule-check/rules/${created.id}`).set('Cookie',student).send({...valid,name:'快照规则（已编辑）'}).expect(200)).body;expect(changed.version).toBe(2);const loaded=await request(app).get(`/api/example-rule-check/reports/${report.id}`).set('Cookie',student).expect(200);expect(loaded.body.rule_snapshots[0].version).toBe(1);expect(loaded.body.rule_snapshots[0].name).toBe('快照规则');await request(app).get(`/api/example-rule-check/reports/${report.id}`).set('Cookie',supervisor).expect(404);});
it('rejects malformed model output rather than fabricating a rule',async()=>{const document=await repo.createDocument('student01','示例.pdf',Buffer.from('%PDF-1.4\nexample'));await repo.updateDocumentAnnotations('student01',document.id,[{type:'focus',page_number:1,text_excerpt:'示例文字'}]);const previous=process.env.DEEPSEEK_API_KEY;process.env.DEEPSEEK_API_KEY='test';const fetchMock=vi.fn(async()=>new Response(JSON.stringify({choices:[{message:{content:'{"title":"missing fields"}'}}]}),{status:200,headers:{'content-type':'application/json'}}));const oldFetch=global.fetch;global.fetch=fetchMock;try{await expect(service.generateRule('student01',{intent:'检查',document_ids:[document.id],external_processing_consent:true})).rejects.toMatchObject({status:400});expect(fetchMock).toHaveBeenCalledOnce();}finally{global.fetch=oldFetch;if(previous===undefined)delete process.env.DEEPSEEK_API_KEY;else process.env.DEEPSEEK_API_KEY=previous;}});
});
