import { FilePlus2, FlaskConical, Lightbulb, LockKeyhole, Sparkles, Upload } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Button, Card, EmptyState, ErrorState, LoadingState, PageHeader, StatusBadge } from '../components/ui';
import { createExampleRule, generateExampleRule, listExampleDocuments, trialExampleRule, updateExampleAnnotations, uploadExampleDocument, type ExampleAnnotation, type ExampleDocument, type RuleDefinition } from '../api/exampleRuleCheck';

const emptyRule: RuleDefinition = { title: '', check_description: '', criteria: [], exception_notes: [], suggestion_template: '' };
const labels: Record<ExampleAnnotation['type'], string> = { focus: '关注内容', pass: '合格示例', fail: '不合格示例', exception: '例外情况', note: '补充说明' };

export default function ExampleRuleCheckPage() {
  const navigate = useNavigate(); const [documents, setDocuments] = useState<ExampleDocument[] | null>(null); const [activeId, setActiveId] = useState(''); const [intent, setIntent] = useState(''); const [rule, setRule] = useState<RuleDefinition>(emptyRule); const [ruleName, setRuleName] = useState(''); const [consent, setConsent] = useState(false); const [busy, setBusy] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [draft, setDraft] = useState<ExampleAnnotation>({ type: 'focus', page_number: 1, text_excerpt: '', note: '' });
  useEffect(() => { listExampleDocuments().then(setDocuments).catch((e) => setError(e.message)); }, []);
  const active = documents?.find((item) => item.id === activeId) || documents?.[0] || null;
  const annotatedIds = useMemo(() => documents?.filter((item) => item.annotations.length > 0).map((item) => item.id) || [], [documents]);
  async function upload(file?: File) { if (!file) return; setBusy('upload'); try { const item = await uploadExampleDocument(file); setDocuments((items) => [item, ...(items || [])]); setActiveId(item.id); setNotice('示例已添加。请在原文中找到能说明规则的证据，再完成标注。'); } catch (e) { setError(e instanceof Error ? e.message : '上传失败'); } finally { setBusy(null); } }
  async function annotate() { if (!active) return setError('请先选择一份示例 PDF'); setBusy('annotation'); try { const item = await updateExampleAnnotations(active.id, [...active.annotations, draft]); setDocuments((items) => items?.map((x) => x.id === item.id ? item : x) || []); setDraft({ type: 'focus', page_number: draft.page_number, text_excerpt: '', note: '' }); setNotice('证据已记录到当前示例。'); } catch (e) { setError(e instanceof Error ? e.message : '保存标注失败'); } finally { setBusy(null); } }
  async function generate() { if (!consent) return setError('请先确认允许将选中的示例文本发送至 DeepSeek。'); setBusy('generate'); try { const next = await generateExampleRule(intent, annotatedIds); setRule(next); setRuleName(next.title); setNotice('规则草稿已生成。请先检查判定条件，再用示例试跑。'); } catch (e) { setError(e instanceof Error ? e.message : '生成失败'); } finally { setBusy(null); setConsent(false); } }
  async function trial() { if (!consent) return setError('每次试跑前都需要再次确认外发。'); setBusy('trial'); try { const result = await trialExampleRule({ name: ruleName || rule.title, intent, definition: rule, document_ids: annotatedIds }); setNotice(`示例试跑已完成：${result.rule_results.map((item) => item.outcome).join('、')}。请结合原文人工复核。`); } catch (e) { setError(e instanceof Error ? e.message : '试跑失败'); } finally { setBusy(null); setConsent(false); } }
  async function save() { setBusy('save'); try { await createExampleRule({ name: ruleName || rule.title, intent, status: 'enabled', definition: rule }); navigate('/example-rule-check/rules'); } catch (e) { setError(e instanceof Error ? e.message : '保存失败'); } finally { setBusy(null); } }
  if (!documents) return <LoadingState label="正在准备个人规则工作台…" />;
  return <div className="space-y-6">
    <PageHeader title="示例规则检测" description="把你能解释的好坏案例转化为可复用的个人检测规则。它不会影响学校规范性检测或既有报告。" actions={<><Link to="/example-rule-check/rules"><Button variant="secondary">规则管理</Button></Link><Link to="/example-rule-check/reports"><Button variant="secondary">检测报告</Button></Link></>} />
    <div className="grid gap-3 md:grid-cols-3">{[['01','选择示例与证据'],['02','说明检查意图'],['03','验证并保存规则']].map(([n, text], i) => <div key={n} className={`rounded-xl border p-4 ${i === (rule.title ? 2 : annotatedIds.length ? 1 : 0) ? 'border-brand-300 bg-brand-50' : 'border-slate-200 bg-white'}`}><span className="text-xs font-black text-brand-600">{n}</span><p className="mt-1 font-bold text-slate-800">{text}</p></div>)}</div>
    {error && <ErrorState title="本次操作未完成" message={error} />}{notice && <div className="rounded-xl border border-brand-200 bg-brand-50 px-4 py-3 text-sm text-brand-800">{notice}</div>}
    <Card title="建立证据集" description="上传 1–5 份有文字层的示例 PDF。请用“页码 + 原文摘录”记录可复核的依据。" actions={<StatusBadge tone={documents.length ? 'info' : 'neutral'}>{documents.length}/5 份示例</StatusBadge>}>
      <label className="flex cursor-pointer items-center justify-center gap-2 rounded-xl border-2 border-dashed border-slate-300 bg-slate-50 px-5 py-5 text-sm font-bold text-slate-600 hover:border-brand-400 hover:bg-brand-50"><Upload className="size-4" />添加示例 PDF<input aria-label="上传示例 PDF" className="sr-only" type="file" accept="application/pdf,.pdf" disabled={busy !== null || documents.length >= 5} onChange={(e) => void upload(e.target.files?.[0])} /></label>
      {documents.length === 0 ? <div className="mt-4"><EmptyState title="还没有示例" description="建议准备一份合格案例和一份典型问题案例，规则会更容易验证。" /></div> : <div className="mt-5 grid gap-4 lg:grid-cols-[220px_minmax(0,1fr)_340px]"><aside className="space-y-2">{documents.map((item) => <button type="button" key={item.id} onClick={() => setActiveId(item.id)} className={`w-full rounded-lg border p-3 text-left ${item.id === active?.id ? 'border-brand-400 bg-brand-50' : 'border-slate-200 hover:border-slate-300'}`}><p className="truncate text-sm font-bold">{item.source_filename}</p><p className="mt-1 text-xs text-slate-500">{item.annotations.length} 条证据</p></button>)}</aside><div className="overflow-hidden rounded-xl border border-slate-200 bg-slate-100"><iframe className="h-[520px] w-full" title="示例 PDF 原文" src={`/api/example-rule-check/documents/${active?.id}/pdf#page=${draft.page_number}`} /></div><section className="rounded-xl border border-slate-200 p-4"><div className="flex items-center gap-2"><FilePlus2 className="size-4 text-brand-600" /><h3 className="font-bold">添加原文证据</h3></div><p className="mt-1 text-xs leading-5 text-slate-500">阅读左侧原文，记录文本、图表、表格或公式对应的页码与摘录。</p><div className="mt-4 space-y-3"><select className="w-full rounded-lg border p-2 text-sm" value={draft.type} onChange={(e) => setDraft((x) => ({ ...x, type: e.target.value as ExampleAnnotation['type'] }))}>{Object.entries(labels).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select><input className="w-full rounded-lg border p-2 text-sm" aria-label="页码" type="number" min="1" value={draft.page_number} onChange={(e) => setDraft((x) => ({ ...x, page_number: Number(e.target.value) }))} /><textarea className="min-h-28 w-full rounded-lg border p-2 text-sm" placeholder="从 PDF 摘录能支持判断的原文" value={draft.text_excerpt} onChange={(e) => setDraft((x) => ({ ...x, text_excerpt: e.target.value }))} /><input className="w-full rounded-lg border p-2 text-sm" placeholder="为什么这段内容重要（可选）" value={draft.note} onChange={(e) => setDraft((x) => ({ ...x, note: e.target.value }))} /><Button className="w-full" disabled={busy !== null || !draft.text_excerpt.trim()} onClick={() => void annotate()}>保存这条证据</Button></div></section></div>}
    </Card>
    <Card title="把证据转成检查意图" description="用自己的话说明希望发现什么；系统不会替你猜测业务标准。"><textarea className="min-h-28 w-full rounded-xl border border-slate-300 p-3 text-sm" placeholder="例如：检查实验结果中的关键结论是否有相应数据、图表或公式支撑" value={intent} onChange={(e) => setIntent(e.target.value)} /><div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-lg bg-slate-50 p-3"><label className="flex items-start gap-2 text-sm text-slate-700"><input className="mt-1" type="checkbox" checked={consent} onChange={(e) => setConsent(e.target.checked)} /><span><b>允许本次外发</b><br />仅会向 DeepSeek 发送选中的示例证据和检查意图。</span></label><Button disabled={busy !== null || !intent.trim() || annotatedIds.length === 0 || !consent} onClick={() => void generate()}>{busy === 'generate' ? '正在生成…' : <><Sparkles className="size-4" />生成规则草稿</>}</Button></div></Card>
    {rule.title && <Card title="审阅并验证规则" description="先检查规则的可解释性，再通过示例试跑决定是否保存。" actions={<StatusBadge tone="warning">人工复核必需</StatusBadge>}><div className="grid gap-4 lg:grid-cols-2"><div className="space-y-3"><input className="w-full rounded-lg border p-2 text-sm font-bold" placeholder="规则名称" value={ruleName} onChange={(e) => setRuleName(e.target.value)} /><textarea className="min-h-28 w-full rounded-lg border p-2 text-sm" value={rule.check_description} onChange={(e) => setRule((x) => ({ ...x, check_description: e.target.value }))} /><textarea className="min-h-36 w-full rounded-lg border p-2 text-sm" placeholder="每行一条判定条件" value={rule.criteria.join('\n')} onChange={(e) => setRule((x) => ({ ...x, criteria: e.target.value.split('\n').filter(Boolean) }))} /></div><div className="rounded-xl bg-slate-50 p-5"><Lightbulb className="size-5 text-brand-600" /><h3 className="mt-3 font-bold">保存前检查</h3><ul className="mt-2 space-y-2 text-sm text-slate-600"><li>• 是否能从证据中看出“通过”和“问题”的区别？</li><li>• 是否已写明不适用或例外的情况？</li><li>• 是否需要更多代表性示例？</li></ul><label className="mt-5 flex gap-2 text-sm"><input type="checkbox" checked={consent} onChange={(e) => setConsent(e.target.checked)} />确认本次试跑允许外发</label><div className="mt-4 flex gap-3"><Button variant="secondary" disabled={busy !== null || !consent} onClick={() => void trial()}>{busy === 'trial' ? '试跑中…' : <><FlaskConical className="size-4" />示例试跑</>}</Button><Button disabled={busy !== null} onClick={() => void save()}>{busy === 'save' ? '保存中…' : '保存个人规则'}</Button></div></div></div></Card>}
    <div className="flex items-center gap-2 text-xs text-slate-500"><LockKeyhole className="size-3.5" />示例、规则和报告仅对当前创建者可见。</div>
  </div>;
}
